name: Run Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.12", "3.13"]
      fail-fast: true
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run Tests
        run: uv run pytest -v --cov=src/knerf --cov-report=xml:coverage.xml

      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: knerf
          flags: unittests
          env_vars: OS,PYTHON
